name: Node.js CI

on:
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: self-hosted
    name: Build Job
    env:
      CI: ""
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: |
          npm install
          npm run build --if-present

