on:
  push:
    branches:
      - "main"
  pull_request:
    types: [closed]
    branches:
      - "main"

jobs:
  build_and_deploy_job:
    runs-on: self-hosted
    name: Build and Deploy Job
    env:
      BUILD_PATH : /root/Website/build
    steps:
      - uses: actions/checkout@v3
      - name: Build And Deploy
        run: |
          npm install
          npm run build
