name: Node.js CI

on:
  pull_request:
    branches: ["main", "dev"]

jobs:
  build:
    runs-on: self-hosted
    name: Build Job
    env:
      CI: ""
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: |
          npm install
          npm run build --if-present
  displayDevEnv:
    runs-on: self-hosted
    name: Deploy to dev env
    env:
      PR_NUMBER: ${{ github.event.number }} + 3000
      CI: ""
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: |
          npm install
          PORT={$PR_NUMBER} npm start
